-- CreateEnum
CREATE TYPE "BoogiOutDiscordOutboxKind" AS ENUM ('CREATE_PROMO', 'NEW_APPLICATION_PLANNER_DM', 'STANDBY_HEADCOUNT_MET', 'REMINDER_3D_CHANNEL', 'POST_CLOSE_DM', 'AFTER_PARTY_SPLIT', 'CREATE_ATTENDANCE_THREAD');

-- CreateEnum
CREATE TYPE "BoogiOutDiscordOutboxStatus" AS ENUM ('PENDING', 'DONE', 'FAILED');
